//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSIQkeyboardManagerPlugin\src\main\java\com\ashera\iqkeyboardmanager\IQkeyboardManagerImpl.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_IQkeyboardManagerImpl")
#ifdef RESTRICT_IQkeyboardManagerImpl
#define INCLUDE_ALL_IQkeyboardManagerImpl 0
#else
#define INCLUDE_ALL_IQkeyboardManagerImpl 1
#endif
#undef RESTRICT_IQkeyboardManagerImpl

#if !defined (ASIQkeyboardManagerImpl_) && (INCLUDE_ALL_IQkeyboardManagerImpl || defined(INCLUDE_ASIQkeyboardManagerImpl))
#define ASIQkeyboardManagerImpl_

#define RESTRICT_IAttributable 1
#define INCLUDE_ASIAttributable 1
#include "IAttributable.h"

@class ASWidgetAttribute;
@class NSString;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;

@interface ASIQkeyboardManagerImpl : NSObject < ASIAttributable >

#pragma mark Public

- (instancetype)init;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (NSString *)getLocalName;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (id<ASIAttributable>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

#pragma mark Package-Private

@end

J2OBJC_EMPTY_STATIC_INIT(ASIQkeyboardManagerImpl)

inline NSString *ASIQkeyboardManagerImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASIQkeyboardManagerImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASIQkeyboardManagerImpl, LOCAL_NAME, NSString *)

FOUNDATION_EXPORT void ASIQkeyboardManagerImpl_init(ASIQkeyboardManagerImpl *self);

FOUNDATION_EXPORT ASIQkeyboardManagerImpl *new_ASIQkeyboardManagerImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASIQkeyboardManagerImpl *create_ASIQkeyboardManagerImpl_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASIQkeyboardManagerImpl)

@compatibility_alias ComAsheraIqkeyboardmanagerIQkeyboardManagerImpl ASIQkeyboardManagerImpl;


#endif

#pragma pop_macro("INCLUDE_ALL_IQkeyboardManagerImpl")
