//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSIQkeyboardManagerPlugin\src\main\java\com\ashera\iqkeyboardmanager\IQPreviousNextViewImpl.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_IQPreviousNextViewImpl")
#ifdef RESTRICT_IQPreviousNextViewImpl
#define INCLUDE_ALL_IQPreviousNextViewImpl 0
#else
#define INCLUDE_ALL_IQPreviousNextViewImpl 1
#endif
#undef RESTRICT_IQPreviousNextViewImpl

#if !defined (ASIQPreviousNextViewImpl_) && (INCLUDE_ALL_IQPreviousNextViewImpl || defined(INCLUDE_ASIQPreviousNextViewImpl))
#define ASIQPreviousNextViewImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASWidgetAttribute;
@class IOSClass;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASIQPreviousNextViewImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(int32_t)index;

- (id)asNativeWidget;

- (id)asWidget;

- (bool)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (bool)removeWithInt:(int32_t)index;

- (bool)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(bool)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASIQPreviousNextViewImpl)

inline NSString *ASIQPreviousNextViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASIQPreviousNextViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASIQPreviousNextViewImpl, LOCAL_NAME, NSString *)

inline NSString *ASIQPreviousNextViewImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASIQPreviousNextViewImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASIQPreviousNextViewImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASIQPreviousNextViewImpl_init(ASIQPreviousNextViewImpl *self);

FOUNDATION_EXPORT ASIQPreviousNextViewImpl *new_ASIQPreviousNextViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASIQPreviousNextViewImpl *create_ASIQPreviousNextViewImpl_init(void);

FOUNDATION_EXPORT void ASIQPreviousNextViewImpl_initWithNSString_(ASIQPreviousNextViewImpl *self, NSString *localname);

FOUNDATION_EXPORT ASIQPreviousNextViewImpl *new_ASIQPreviousNextViewImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASIQPreviousNextViewImpl *create_ASIQPreviousNextViewImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASIQPreviousNextViewImpl_initWithNSString_withNSString_(ASIQPreviousNextViewImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASIQPreviousNextViewImpl *new_ASIQPreviousNextViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASIQPreviousNextViewImpl *create_ASIQPreviousNextViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASIQPreviousNextViewImpl)

@compatibility_alias ComAsheraIqkeyboardmanagerIQPreviousNextViewImpl ASIQPreviousNextViewImpl;


#endif

#if !defined (ASIQPreviousNextViewImpl_IQPreviousNextViewExt_) && (INCLUDE_ALL_IQPreviousNextViewImpl || defined(INCLUDE_ASIQPreviousNextViewImpl_IQPreviousNextViewExt))
#define ASIQPreviousNextViewImpl_IQPreviousNextViewExt_

#define RESTRICT_FrameLayout 1
#define INCLUDE_ADFrameLayout 1
#include "FrameLayout.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASIQPreviousNextViewImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASIQPreviousNextViewImpl_IQPreviousNextViewExt : ADFrameLayout < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASIQPreviousNextViewImpl:(ASIQPreviousNextViewImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (int32_t)getMaxHeight;

- (int32_t)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(int32_t)offset;

- (void)offsetTopAndBottomWithInt:(int32_t)offset;

- (void)onMeasureWithInt:(int32_t)widthMeasureSpec
                 withInt:(int32_t)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(int32_t)height;

- (void)setMaxWidthWithInt:(int32_t)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(int32_t)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(int32_t)width
                               withInt:(int32_t)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(bool)changed
                    withInt:(int32_t)l
                    withInt:(int32_t)t
                    withInt:(int32_t)r
                    withInt:(int32_t)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASIQPreviousNextViewImpl_IQPreviousNextViewExt)

FOUNDATION_EXPORT void ASIQPreviousNextViewImpl_IQPreviousNextViewExt_initWithASIQPreviousNextViewImpl_(ASIQPreviousNextViewImpl_IQPreviousNextViewExt *self, ASIQPreviousNextViewImpl *outer$);

FOUNDATION_EXPORT ASIQPreviousNextViewImpl_IQPreviousNextViewExt *new_ASIQPreviousNextViewImpl_IQPreviousNextViewExt_initWithASIQPreviousNextViewImpl_(ASIQPreviousNextViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASIQPreviousNextViewImpl_IQPreviousNextViewExt *create_ASIQPreviousNextViewImpl_IQPreviousNextViewExt_initWithASIQPreviousNextViewImpl_(ASIQPreviousNextViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASIQPreviousNextViewImpl_IQPreviousNextViewExt)


#endif

#pragma pop_macro("INCLUDE_ALL_IQPreviousNextViewImpl")
